### ISSUE TITLE
Add public roadmap to show the upcoming developments

### ISSUE THREAD

**Issue by Greenheart** [Greenheart/idg.tools#198]
This will help answer common questions.

Either add this on the webpage - or as a public GitHub project that can be updated and integrated with the rest of the project management. However things might not be as well-written in the issues and projects here on GitHub so linking to a roadmap page on the website would likely help a lot.

We'll start with the webpage.

- [x] Create roadmap page - formatted list of items and possibly a short description
- [x] Consider adding links to the public roadmap in the forms to submit feedback and submit new tools.
- [x] Also encourage to read the public roadmap before suggesting new features via the feedback forms on tool pages.
