### ISSUE TITLE
Add widget for random IDG symbol

### ISSUE THREAD

**Issue by Greenheart** [Greenheart/idg.tools#436]
- When visiting https://idg.tools/symbols, you should get a random symbol.
- Maybe also show the skill name. Would be good to connect the skill symbols to the skill IDs to reduce the data needed.

## TODO
- [x] Create route /symbols
- [x] Show a random symbol based on the assets and the known file name
- [x] Optimise SVGs (minify and remove embedded classes - let styling be handled by the app)
- [x] Refactor the IDGSymbol component and use proper SVG files instead of inline SVGs to enable browser caching
- [x] Fix route so it shows up without any other page layout.
