### ISSUE TITLE
Prepare content for the IDG field kit launch

### ISSUE THREAD

**Issue by Greenheart** [Greenheart/idg.tools#97]
This is a follow-up to https://github.com/Greenheart/idg.tools/pull/76

# TODO before publishing the IDG field kit
- [x] Replace `FIELD_KIT_LINK` with the actual published PDF.
- [x] Ensure all IDG Field Kit mentions are consistent with the actual name of the publication.
- [x] Get feedback on how to adapt the descriptions - Should we use 1) The most important sections from the full descriptions, or 2) Always use the full description but only show the start, and then a button to "show more"? Alternatively, add "This is an adapted version" notice at the top of the description in IDG.tools, and link to the full PDF from the start, to give a concise summary and then link to the full details for curious readers.
- [x] Talk to the IDG team - we need to adapt the language in the Field Kit to be much more accessible on IDG.tools (less academic and with a clear structure of benefits, connection to SDGs & IDGs etc)
- [x] Help needed: Review IDG skill relevancy for IDG.tools and the digital field kit - we've done best guess estimates to have a starting point, and want to invite everyone to give feedback to help improve things.
- [x] Question: Are everyone OK with the content using the specific version of creative commons that we suggest? If not, which variation would you prefer and why?
- [x] For the launch presentation, and the landing page of IDG.tools - invite communicators, writers, developers, designers and project managers to help co-create the IDGs community platform.
- [x] Improve "Personal Growth through a Polarity Lens"
- [x] Decision: How do we include contributors to each tool and give credit? Should we list names at the bottom, or should we do more like Wikipedia and keep it focused on the content rather than the people behind? It is also hard to keep track of exactly who wrote which text.
- [x] Ensure all texts are updated and improved to match latest Field Kit version.
- [x] For "Methods for scaffolding collaboration on complex issues", we should ideally add tools for each one of the suggested methods.
- [x] Fix long link rendering in resources for "compassion training"

**Comment by Greenheart** [comment]
- [ ] fix link text in nature quest to mention the right secrion in the field kit

**Comment by Greenheart** [comment]
Finally! Almost ready for release :smile:
